// SPDX-License-Identifier: GPL-3.0-or-later
// PKHeX 26.08.26 WinForms Resources/text/lang_{zh-Hans,en,ja}.txt; Main.mnu_* labels.
// DeleteForeign describes the actual original-handler predicate, not country or language.
export const boxBatchNames = {
  zh: {
    DeleteAll: "清理所有宝可梦",
    DeleteEggs: "清理所有未孵化",
    DeletePastGen: "清理前代宝可梦",
    DeleteForeign: "删除非本存档初训家的宝可梦",
    DeleteUntrained: "清理无努力值宝可梦",
    DeleteItemless: "清理无持有物宝可梦",
    DeleteIllegal: "清理非法宝可梦",
    DeleteClones: "清理重复宝可梦",
    SortSpecies: "按图鉴编号(升序)",
    SortSpeciesReverse: "按图鉴编号(降序)",
    SortLevel: "按等级(升序)",
    SortLevelReverse: "按等级(降序)",
    SortDate: "按相遇日期",
    SortName: "按种类",
    SortFavorite: "收藏标记",
    SortParty: "同行队伍排序",
    SortShiny: "按是否异色",
    SortAlpha: "头目",
    SortRandom: "随机",
    SortUsage: "按亲密度",
    SortPotential: "按个体值和",
    SortTraining: "按努力值和",
    SortOwner: "按初训家",
    SortType: "按属性",
    SortTypeTera: "按太晶属性",
    SortVersion: "按来源版本",
    SortBST: "按种族值和",
    SortCP: "CP",
    SortScale: "按大小",
    SortRibbons: "丝带计数",
    SortMarks: "标记计数",
    SortLegal: "按合法性",
    SortEncounterType: "按相遇类型",
    ModifyHatchEggs: "使蛋孵化",
    ModifyMaxFriendship: "使亲密度最大",
    ModifyMaxLevel: "使等级最大",
    ModifyResetMoves: "填入建议招式",
    ModifyRandomMoves: "填入随机招式",
    ModifyHyperTrain: "进行极限训练",
    ModifyGanbaru: "使奋斗等级最大",
    ModifyRemoveNicknames: "重置昵称",
    ModifyRemoveItem: "清空持有物",
    ModifyHeal: "修复(能力/PP)",
  },
  en: {
    DeleteAll: "Clear",
    DeleteEggs: "Eggs",
    DeletePastGen: "Past Generation",
    DeleteForeign: "Delete Pokémon from other Original Trainers",
    DeleteUntrained: "Untrained",
    DeleteItemless: "No Held Item",
    DeleteIllegal: "Illegal",
    DeleteClones: "Clones",
    SortSpecies: "Pokédex No.",
    SortSpeciesReverse: "Pokédex No. (Reverse)",
    SortLevel: "Level (Low to High)",
    SortLevelReverse: "Level (High to Low)",
    SortDate: "Met Date",
    SortName: "Species Name",
    SortFavorite: "Favorite Mark",
    SortParty: "Party",
    SortShiny: "Shiny",
    SortAlpha: "Alpha",
    SortRandom: "Random",
    SortUsage: "Usage",
    SortPotential: "IV Potential",
    SortTraining: "EV Training",
    SortOwner: "Ownership",
    SortType: "Type",
    SortTypeTera: "Tera Type",
    SortVersion: "Version",
    SortBST: "Base Stat Total",
    SortCP: "CP",
    SortScale: "Scale",
    SortRibbons: "Ribbon Count",
    SortMarks: "Mark Count",
    SortLegal: "Legal",
    SortEncounterType: "Encounter Type",
    ModifyHatchEggs: "Hatch Eggs",
    ModifyMaxFriendship: "Max Friendship",
    ModifyMaxLevel: "Max Level",
    ModifyResetMoves: "Reset Moves",
    ModifyRandomMoves: "Randomize Moves",
    ModifyHyperTrain: "Hyper Train",
    ModifyGanbaru: "Max All GVs",
    ModifyRemoveNicknames: "Remove Nicknames",
    ModifyRemoveItem: "Delete Held Item",
    ModifyHeal: "Heal (Stats/PP)",
  },
  ja: {
    DeleteAll: "クリア",
    DeleteEggs: "タマゴ",
    DeletePastGen: "過去世代",
    DeleteForeign: "このセーブの親と一致しないポケモンを削除",
    DeleteUntrained: "未育成",
    DeleteItemless: "道具なし",
    DeleteIllegal: "不正",
    DeleteClones: "複製",
    SortSpecies: "ポケモン図鑑番号",
    SortSpeciesReverse: "ポケモン図鑑番号(逆の順序)",
    SortLevel: "レベル(低い順)",
    SortLevelReverse: "レベル(高い順)",
    SortDate: "出会った日",
    SortName: "種族名",
    SortFavorite: "お気に入りマーク",
    SortParty: "手持ちポケモン",
    SortShiny: "色違い",
    SortAlpha: "オヤブン",
    SortRandom: "ランダム",
    SortUsage: "使用率",
    SortPotential: "個体値",
    SortTraining: "努力値",
    SortOwner: "親名",
    SortType: "タイプ",
    SortTypeTera: "テラスタイプ",
    SortVersion: "バージョン",
    SortBST: "種族値合計",
    SortCP: "CP",
    SortScale: "サイズ",
    SortRibbons: "リボン数",
    SortMarks: "あかし",
    SortLegal: "正規",
    SortEncounterType: "エンカウントタイプ",
    ModifyHatchEggs: "タマゴを孵化",
    ModifyMaxFriendship: "なかよし度最大",
    ModifyMaxLevel: "レベル最大",
    ModifyResetMoves: "わざを初期化",
    ModifyRandomMoves: "ランダムわざ",
    ModifyHyperTrain: "すごいとっくん",
    ModifyGanbaru: "がんばレベル最大",
    ModifyRemoveNicknames: "ニックネームを消去",
    ModifyRemoveItem: "道具をはずす",
    ModifyHeal: "回復(HP/PP)",
  },
};
