export const gbSpecialWords = {
  zh: {
    firstNote: "修改捕获率和保存的属性，修改后可重新检查合法性。",
    title: "世代专属记录",
    catchRate: "捕获率",
    type1: "第一属性",
    type2: "第二属性",
    metLevel: "捕获等级",
    metLocation: "捕获地点",
    metTimeOfDay: "捕获时段",
    trainerGender: "原训练家性别",
    pokerusStrain: "宝可病毒菌株",
    pokerusDays: "宝可病毒剩余天数",
    times: ["未记录", "早晨", "白天", "夜晚"],
    apply: "应用记录修改",
    current: "当前值",
    clearRate: "清空捕获率",
    note: "只修改表单中列出的记录。第二世代的捕获信息主要由《水晶版》记录；修改后可重新检查合法性。",
    virusNote:
      "菌株和剩余天数决定感染状态，天数上限随菌株变化。原有特殊数值可以保持不变；主动修改时按所选菌株检查。",
    invalid: "请检查记录范围、目录选项及宝可病毒菌株对应的天数上限。",
    naming: "名称与蛋操作",
    nameOnly: "恢复种类名称",
    language: "名称语言",
    restoreName: "使用种类名称",
    nameNote:
      "所选语言用于恢复种类名称或命名蛋，可选范围由当前文件的文字编码决定。",
    eggNote:
      "转换为蛋会更新蛋标记、名称和孵化周期；孵化会更新名称、亲密度与孵化地点。操作可撤销。",
    cycleError: "剩余孵化周期必须为 0–255 的整数。",
  },
  en: {
    firstNote:
      "Edit the catch rate and stored types. Check legality again after editing.",
    title: "Generation-specific records",
    catchRate: "Catch rate",
    type1: "First type",
    type2: "Second type",
    metLevel: "Met level",
    metLocation: "Met location",
    metTimeOfDay: "Time of day",
    trainerGender: "Original trainer gender",
    pokerusStrain: "Pokérus strain",
    pokerusDays: "Pokérus days remaining",
    times: ["Not recorded", "Morning", "Day", "Night"],
    apply: "Apply record changes",
    current: "Current value",
    clearRate: "Clear catch rate",
    note: "Edit the records listed here. Generation II met details are primarily recorded by Crystal. Check legality again after editing.",
    virusNote:
      "Strain and remaining days determine infection status. The maximum duration depends on the strain. Existing unusual values can remain unchanged; edits are checked against the selected strain.",
    invalid:
      "Check record ranges, catalog choices and the maximum duration for the selected Pokérus strain.",
    naming: "Names and Egg operations",
    nameOnly: "Restore species name",
    language: "Name language",
    restoreName: "Use species name",
    nameNote:
      "This language is used when restoring a species name or naming an Egg. Available languages depend on the file's text encoding.",
    eggNote:
      "Creating an Egg updates its marker, name and hatch cycles. Hatching updates the name, friendship and hatch location. These operations can be undone.",
    cycleError: "Remaining hatch cycles must be an integer from 0 to 255.",
  },
  ja: {
    firstNote:
      "捕獲率と保存されているタイプを編集します。変更後は合法性を再確認できます。",
    title: "世代固有の記録",
    catchRate: "捕獲率",
    type1: "タイプ1",
    type2: "タイプ2",
    metLevel: "出会ったレベル",
    metLocation: "出会った場所",
    metTimeOfDay: "出会った時間帯",
    trainerGender: "親の性別",
    pokerusStrain: "ポケルス株",
    pokerusDays: "ポケルス残り日数",
    times: ["記録なし", "朝", "昼", "夜"],
    apply: "記録の変更を適用",
    current: "現在値",
    clearRate: "捕獲率をクリア",
    note: "表示されている記録を編集します。第二世代の出会った情報は主に『クリスタル』で記録されます。変更後は合法性を再確認できます。",
    virusNote:
      "株と残り日数によって感染状態が決まり、日数の上限は株によって変わります。元の特殊な値は保持できますが、変更時は選択した株の上限を確認します。",
    invalid:
      "記録の範囲、選択肢、ポケルス株に対応する日数の上限を確認してください。",
    naming: "名前とタマゴの操作",
    nameOnly: "種族名に戻す",
    language: "名前の言語",
    restoreName: "種族名を使用",
    nameNote:
      "種族名に戻す場合やタマゴの命名に使用する言語です。選択可能な言語はファイルの文字コードによって決まります。",
    eggNote:
      "タマゴへの変更で識別子・名前・孵化サイクルを更新します。孵化では名前・なつき度・孵化場所を更新します。操作は元に戻せます。",
    cycleError: "残り孵化サイクルは 0–255 の整数で指定してください。",
  },
};
