export const dex4Labels = {
  zh: {
    upgrade: "图鉴解锁",
    applyUpgrade: "应用解锁状态",
    species: "选择宝可梦",
    genders: "见过的性别（按出现顺序）",
    forms: "见过的形态（按出现顺序）",
    languages: "已记录语言",
    noLanguages: "这个版本不记录该宝可梦的外语信息。",
    none: "尚未选择",
    add: "添加",
    remove: "移除",
    up: "上移",
    down: "下移",
    genderless: "无性别",
    scope: "批量范围",
    one: "当前宝可梦",
    all: "全部 493 种",
    run: "应用批量操作",
    action: "操作",
    clear: "清除见过及关联记录",
    seen: "全部见过",
    caught: "全部捕获",
    uncaught: "清除捕获及语言",
    complete: "完整图鉴记录",
    note: "清除见过会清除捕获、性别、形态与语言；清除捕获也会清除语言。批量操作直接应用到工作副本，可以撤销。",
    dirty: "当前条目有草稿，请先应用或重置后再切换宝可梦或执行其他操作。",
    format: "形态按本版本的 PKHeX 编码保存，应用后以重新读取的记录为准。",
  },
  en: {
    upgrade: "Pokédex unlock",
    applyUpgrade: "Apply unlock state",
    species: "Choose Pokémon",
    genders: "Seen genders (in encounter order)",
    forms: "Seen forms (in encounter order)",
    languages: "Recorded languages",
    noLanguages:
      "This version does not record foreign languages for this species.",
    none: "None selected",
    add: "Add",
    remove: "Remove",
    up: "Move up",
    down: "Move down",
    genderless: "Genderless",
    scope: "Batch scope",
    one: "Current Pokémon",
    all: "All 493 species",
    run: "Apply batch operation",
    action: "Operation",
    clear: "Clear seen and related records",
    seen: "Seen all",
    caught: "Caught all",
    uncaught: "Clear caught and languages",
    complete: "Complete Pokédex records",
    note: "Clearing seen also clears caught, genders, forms and languages. Clearing caught also clears languages. Batch operations apply to the working copy and can be undone.",
    dirty:
      "Apply or reset this entry draft before changing species or running another operation.",
    format:
      "Forms use this version's PKHeX encoding. The reloaded records are shown after applying.",
  },
  ja: {
    upgrade: "図鑑の解放",
    applyUpgrade: "解放状態を適用",
    species: "ポケモンを選択",
    genders: "発見した性別（出現順）",
    forms: "発見したフォルム（出現順）",
    languages: "記録した言語",
    noLanguages:
      "このバージョンでは、このポケモンの外国語情報は記録されません。",
    none: "未選択",
    add: "追加",
    remove: "削除",
    up: "上へ",
    down: "下へ",
    genderless: "性別不明",
    scope: "一括操作の対象",
    one: "現在のポケモン",
    all: "全493種類",
    run: "一括操作を適用",
    action: "操作",
    clear: "発見と関連記録を解除",
    seen: "すべて発見済み",
    caught: "すべて捕獲済み",
    uncaught: "捕獲と言語を解除",
    complete: "図鑑記録を完成",
    note: "発見を解除すると捕獲・性別・フォルム・言語も解除します。捕獲の解除は言語も解除します。一括操作は作業コピーに適用され、取り消せます。",
    dirty:
      "ポケモンの切り替えや別の操作の前に、現在の下書きを適用またはリセットしてください。",
    format:
      "フォルムは本バージョンの PKHeX の形式で保存し、適用後に読み直した記録を表示します。",
  },
};
