export const dex5Labels = {
  zh: {
    globals: "图鉴设置",
    unlocked: "已解锁全国图鉴",
    mode: "显示全国图鉴",
    initial: "打开图鉴时的宝可梦",
    spinda: "晃晃斑图案值（十六进制）",
    hex: "最多 8 个字符；留空为 0，其他非十六进制字符按 PKHeX 规则忽略。",
    applyGlobals: "应用图鉴设置",
    reset: "重置草稿",
    species: "选择宝可梦",
    seen: "见过",
    display: "显示",
    regions: ["雄性／无性别", "雌性", "闪光雄性／无性别", "闪光雌性"],
    formColumns: ["普通见过", "闪光见过", "普通显示", "闪光显示"],
    forms: "形态记录",
    languages: "语言记录",
    noLanguages: "第五世代新增宝可梦不记录外语。",
    shiny: "包含闪光",
    allLanguages: "全部语言",
    action: "批量操作",
    run: "应用操作",
    give: "当前宝可梦：完整记录",
    giveNone: "当前宝可梦：清除见过",
    clear: "全图鉴：清除见过",
    seenAll: "全图鉴：全部见过",
    caught: "全图鉴：全部捕获",
    uncaught: "全图鉴：清除捕获及语言",
    complete: "全图鉴：完整记录",
    formsClear: "全图鉴：清除形态记录",
    formsFirst: "全图鉴：补充首个形态",
    formsAll: "全图鉴：补充全部形态",
    note: "清除见过只清除性别／闪光见过记录，保留捕获、显示、形态和语言。形态操作作用于整个图鉴。所有操作均可撤销。",
    dirty: "请先应用或重置当前草稿，再切换或执行其他操作。",
    korean:
      "存档语言为韩文时，上游单语言批量操作不会自动登记韩文；可勾选全部语言或手动设置韩文。",
    unknown: "原始值",
  },
  en: {
    globals: "Pokédex settings",
    unlocked: "National Pokédex unlocked",
    mode: "Show National Pokédex",
    initial: "Pokémon shown on opening",
    spinda: "Spinda pattern (hex)",
    hex: "Up to 8 characters. Empty means 0; other non-hex characters are ignored as in PKHeX.",
    applyGlobals: "Apply Pokédex settings",
    reset: "Reset draft",
    species: "Choose Pokémon",
    seen: "Seen",
    display: "Displayed",
    regions: [
      "Male / genderless",
      "Female",
      "Shiny male / genderless",
      "Shiny female",
    ],
    formColumns: [
      "Seen regular",
      "Seen shiny",
      "Displayed regular",
      "Displayed shiny",
    ],
    forms: "Form records",
    languages: "Language records",
    noLanguages: "New Generation V species do not store foreign languages.",
    shiny: "Include shiny",
    allLanguages: "All languages",
    action: "Batch operation",
    run: "Apply operation",
    give: "Current Pokémon: complete records",
    giveNone: "Current Pokémon: clear seen",
    clear: "All species: clear seen",
    seenAll: "All species: seen all",
    caught: "All species: caught all",
    uncaught: "All species: clear caught and languages",
    complete: "All species: complete records",
    formsClear: "All species: clear form records",
    formsFirst: "All species: add first form",
    formsAll: "All species: add all forms",
    note: "Clear seen only clears gender/shiny seen records. Caught, displayed, forms and languages remain. Form operations affect the entire Pokédex. All operations can be undone.",
    dirty:
      "Apply or reset the current draft before switching or running another operation.",
    korean:
      "For Korean saves, upstream single-language batch operations do not register Korean automatically. Choose all languages or set Korean manually.",
    unknown: "Stored value",
  },
  ja: {
    globals: "図鑑設定",
    unlocked: "全国図鑑を解放済み",
    mode: "全国図鑑を表示",
    initial: "図鑑を開いたときのポケモン",
    spinda: "パッチールの模様（16進数）",
    hex: "最大8文字。空欄は0、16進数以外の文字はPKHeXと同様に無視します。",
    applyGlobals: "図鑑設定を適用",
    reset: "下書きをリセット",
    species: "ポケモンを選択",
    seen: "発見",
    display: "表示",
    regions: ["♂／性別不明", "♀", "色違い♂／性別不明", "色違い♀"],
    formColumns: ["通常を発見", "色違いを発見", "通常を表示", "色違いを表示"],
    forms: "フォルム記録",
    languages: "言語記録",
    noLanguages: "第五世代で追加されたポケモンは外国語を記録しません。",
    shiny: "色違いを含む",
    allLanguages: "全言語",
    action: "一括操作",
    run: "操作を適用",
    give: "現在のポケモン：記録を完成",
    giveNone: "現在のポケモン：発見を解除",
    clear: "全種類：発見を解除",
    seenAll: "全種類：すべて発見済み",
    caught: "全種類：すべて捕獲済み",
    uncaught: "全種類：捕獲と言語を解除",
    complete: "全種類：記録を完成",
    formsClear: "全種類：フォルム記録を解除",
    formsFirst: "全種類：先頭フォルムを追加",
    formsAll: "全種類：全フォルムを追加",
    note: "発見の解除は性別・色違いの発見記録のみを消去し、捕獲・表示・フォルム・言語は保持します。フォルム操作は図鑑全体が対象です。操作は取り消せます。",
    dirty:
      "切り替えや別の操作の前に現在の下書きを適用またはリセットしてください。",
    korean:
      "韓国語のセーブでは、上流の単一言語一括操作は韓国語を自動登録しません。全言語を選ぶか手動で設定してください。",
    unknown: "保存値",
  },
};
