type Pair = readonly [string, string];
const names: Record<string, Pair> = {
  Off: ["关", "オフ"],
  On: ["开", "オン"],
  None: ["无", "なし"],
  Default: ["默认", "標準"],
  Black: ["黑色", "黒"],
  Brown: ["棕色", "茶色"],
  Honey: ["蜜色", "ハニー"],
  Orange: ["橙色", "オレンジ"],
  Blond: ["金发", "ブロンド"],
  White: ["白色", "白"],
  Light: ["浅色", "ライト"],
  Tan: ["小麦色", "小麦色"],
  Dark: ["深色", "ダーク"],
  Hazel: ["榛色", "ヘーゼル"],
  Green: ["绿色", "緑"],
  Blue: ["蓝色", "青"],
  Red: ["红色", "赤"],
  Yellow: ["黄色", "黄"],
  Pink: ["粉色", "ピンク"],
  Purple: ["紫色", "紫"],
  Gray: ["灰色", "グレー"],
  Beige: ["米色", "ベージュ"],
  Olive: ["橄榄色", "オリーブ"],
  Aqua: ["水蓝色", "アクア"],
  Gold: ["金色", "ゴールド"],
  Silver: ["银色", "シルバー"],
  Metal: ["金属色", "メタル"],
  Denim: ["牛仔布", "デニム"],
  Satin: ["缎面", "サテン"],
  Navy_Blue: ["藏蓝色", "ネイビー"],
  Lime_Green: ["青柠绿", "ライムグリーン"],
  Pale_Pink: ["浅粉色", "ペールピンク"],
  Medium: ["中长发", "ミディアム"],
  Medium_Perm: ["中长卷发", "ミディアムパーマ"],
  Short: ["短发", "ショート"],
  Very_Short: ["超短发", "ベリーショート"],
  Long: ["长发", "ロング"],
  Bob: ["波波头", "ボブ"],
  Ponytail: ["马尾", "ポニーテール"],
  Pigtails: ["双马尾", "ツインテール"],
  Bangs: ["刘海", "前髪あり"],
  Sideswept: ["侧分刘海", "横分け"],
  Accented_Jeans: ["装饰牛仔裤", "アクセントジーンズ"],
  Ankle_Socks: ["短袜", "アンクルソックス"],
  Artificial_Flower_Pin: ["仿花发饰", "造花ピン"],
  Bamboo_Sprig_Hat: ["竹叶帽", "笹飾りの帽子"],
  Barefoot: ["赤脚", "裸足"],
  Boater: ["平顶草帽", "カンカン帽"],
  Bold_Striped_Pants: ["宽条纹长裤", "太ストライプパンツ"],
  Bow_Shoes: ["蝴蝶结鞋", "リボンシューズ"],
  Button_Accessory: ["纽扣饰品", "ボタンアクセサリー"],
  Camo_Cap: ["迷彩帽", "迷彩キャップ"],
  Camo_OTK_Socks: ["迷彩过膝袜", "迷彩ニーハイ"],
  Camo_Pants: ["迷彩长裤", "迷彩パンツ"],
  Checked_Pants: ["格纹长裤", "チェックパンツ"],
  Checkered_Fedora: ["格纹礼帽", "チェック中折れ帽"],
  Chinos: ["休闲长裤", "チノパン"],
  Cross_Laced_Shorts: ["交叉系带短裤", "編み上げショートパンツ"],
  Cuffed_Jeans: ["卷边牛仔裤", "ロールアップジーンズ"],
  Cycling_Cap: ["骑行帽", "サイクルキャップ"],
  Damaged_Jean_Shorts: ["破洞牛仔短裤", "ダメージデニムショーツ"],
  Damaged_Jeans: ["破洞牛仔裤", "ダメージジーンズ"],
  Damaged_Skinny_Jeans: ["破洞紧身牛仔裤", "ダメージスキニージーンズ"],
  Denim_Miniskirt: ["牛仔短裙", "デニムミニスカート"],
  Double_Front_Coat_Dress: ["双排扣外套裙", "ダブルコートワンピース"],
  Down_Jacket: ["羽绒服", "ダウンジャケット"],
  Enamel_Striped_Purse: ["漆皮条纹包", "エナメルストライプバッグ"],
  Exotic_Cap: ["异国风帽", "エキゾチックキャップ"],
  Exotic_Top: ["异国风上衣", "エキゾチックトップス"],
  Feather_Accessory: ["羽毛饰品", "フェザーアクセサリー"],
  Fedora: ["礼帽", "中折れ帽"],
  Felt_Hat: ["毡帽", "フェルトハット"],
  Frilly_Dress: ["褶边连衣裙", "フリルワンピース"],
  Glitzy_Scarf_Top: ["华丽围巾上衣", "華やかなスカーフトップス"],
  Hat_Ribbon_Accessory: ["帽子缎带", "ハットリボン"],
  High_Tops: ["高帮鞋", "ハイカットシューズ"],
  High_Waisted_Outfit: ["高腰套装", "ハイウエストコーデ"],
  Hoodie: ["连帽衫", "パーカー"],
  Jean_Shorts: ["牛仔短裤", "デニムショーツ"],
  King_T_Shirt: ["国王图案T恤", "キングTシャツ"],
  Knee_Socks: ["及膝袜", "ハイソックス"],
  Knit_Cap: ["针织帽", "ニット帽"],
  Laced_Boots: ["系带靴", "レースアップブーツ"],
  Leggings: ["打底裤", "レギンス"],
  Little_Black_Dress: ["小黑裙", "リトルブラックドレス"],
  Loafers: ["乐福鞋", "ローファー"],
  Logo_Cap: ["标志帽", "ロゴキャップ"],
  Logo_T_Shirt: ["标志T恤", "ロゴTシャツ"],
  Mary_Janes: ["玛丽珍鞋", "ストラップシューズ"],
  Metal_Pin: ["金属别针", "メタルピン"],
  Midriff_Halter_Top: ["露腹挂脖上衣", "ホルターネックトップス"],
  No_Socks: ["不穿袜子", "靴下なし"],
  OTK_Socks: ["过膝袜", "ニーハイソックス"],
  Outdoors_Cap: ["户外帽", "アウトドアキャップ"],
  Pajama_Pants: ["睡裤", "パジャマパンツ"],
  Pajama_Top: ["睡衣上装", "パジャマトップス"],
  Plaid_Shirt_Combo: ["格子衬衫组合", "チェックシャツコーデ"],
  Pleated_Kilt_Skirt: ["苏格兰百褶裙", "プリーツキルトスカート"],
  Pleated_Skirt: ["百褶裙", "プリーツスカート"],
  Poke_Ball_Baby_Doll_Tee: ["精灵球娃娃衫", "モンスターボールベビードールT"],
  Punk_OTK_Socks: ["朋克过膝袜", "パンクニーハイ"],
  Ribbon_Purse: ["蝴蝶结包", "リボンバッグ"],
  Ribbon_Smock_Top: ["蝴蝶结罩衫", "リボンスモック"],
  Riding_Boots: ["骑士靴", "ライディングブーツ"],
  Ruffled_Camisole: ["褶边吊带衫", "フリルキャミソール"],
  Ruffled_Tank_Top: ["褶边背心", "フリルタンクトップ"],
  Saddle_Shoes: ["马鞍鞋", "サドルシューズ"],
  Scalloped_Skirt: ["扇边裙", "スカラップスカート"],
  Scalloped_Tiered_Skirt: ["扇边层叠裙", "スカラップティアードスカート"],
  Scarf_Top: ["围巾上衣", "スカーフトップス"],
  Shirt_and_Tie: ["衬衫与领带", "シャツとネクタイ"],
  Short_Boots: ["短靴", "ショートブーツ"],
  Short_Cargo_Pants: ["工装短裤", "カーゴショーツ"],
  Short_Parka: ["短款连帽衫", "ショートパーカー"],
  Single_Front_Coat_Dress: ["单排扣外套裙", "シングルコートワンピース"],
  Single_Stripe_OTK_Socks: ["单条纹过膝袜", "一本ラインニーハイ"],
  Skinny_Jeans: ["紧身牛仔裤", "スキニージーンズ"],
  Sleeveless_Turtleneck: ["无袖高领衫", "ノースリーブタートルネック"],
  Sneakers: ["运动鞋", "スニーカー"],
  Sparkly_Bolero_Dress: ["闪光短外套裙", "きらめくボレロワンピース"],
  Splatter_Paint_T_Shirt: ["泼墨T恤", "スプラッシュペイントTシャツ"],
  Sports_Cap: ["运动帽", "スポーツキャップ"],
  Strappy_Purse: ["背带包", "ストラップバッグ"],
  Striped_Pleated_Skirt: ["条纹百褶裙", "ストライププリーツスカート"],
  Striped_Shirt_Combo: ["条纹衬衫组合", "ストライプシャツコーデ"],
  Striped_Tank_Top: ["条纹背心", "ストライプタンクトップ"],
  Sundae_Dress: ["圣代连衣裙", "サンデーワンピース"],
  Tassel_Purse: ["流苏包", "タッセルバッグ"],
  Tie_Neck_Blouse: ["系带领衬衫", "ボウタイブラウス"],
  Tiered_Satin_Skirt: ["缎面层叠裙", "サテンティアードスカート"],
  Tights: ["连裤袜", "タイツ"],
  Tote_Bag: ["托特包", "トートバッグ"],
  Trench_Coat: ["风衣", "トレンチコート"],
  Twin_T_Shirt: ["双子图案T恤", "ツインTシャツ"],
  Two_Tone_Bag: ["双色包", "ツートーンバッグ"],
  V_Neck_T_Shirt: ["V领T恤", "VネックTシャツ"],
  Vinyl_Messenger_Bag: ["亮面邮差包", "ビニールメッセンジャーバッグ"],
  Vinyl_Pants: ["亮面长裤", "ビニールパンツ"],
  Wide_Frame_Sunglasses: ["宽框太阳镜", "ワイドフレームサングラス"],
  Wide_Stripe_OTK_Socks: ["宽条纹过膝袜", "太ボーダーニーハイ"],
  Zipped_Boots: ["拉链靴", "ジップブーツ"],
  Zipped_Jacket: ["拉链夹克", "ジップジャケット"],
  Zipped_Shirt_Combo: ["拉链衬衫组合", "ジップシャツコーデ"],
};
export const appearanceFieldNames: Record<string, Pair> = {
  Version: ["外观版本", "外見バージョン"],
  Model: ["模型", "モデル"],
  Skin: ["肤色", "肌色"],
  HairColor: ["发色", "髪色"],
  Hat: ["帽子", "帽子"],
  Front: ["前发", "前髪"],
  Hair: ["发型", "髪型"],
  Face: ["脸型编号", "顔の番号"],
  Arms: ["手臂编号", "腕の番号"],
  Top: ["上衣", "トップス"],
  Legs: ["下装", "ボトムス"],
  Dress: ["连衣裙", "ワンピース"],
  Socks: ["袜子", "靴下"],
  Shoes: ["鞋子", "靴"],
  Bag: ["包", "バッグ"],
  AHat: ["帽饰", "帽子の飾り"],
  Contacts: ["隐形眼镜", "コンタクト"],
  ColorContacts: ["隐形眼镜颜色", "コンタクトの色"],
  FacialHair: ["面部毛发编号", "ひげの番号"],
  FacialColor: ["面部毛发颜色编号", "ひげの色番号"],
  PaintLeft: ["左侧彩绘编号", "左のフェイスペイント番号"],
  PaintRight: ["右侧彩绘编号", "右のフェイスペイント番号"],
  PaintLeftC: ["左侧彩绘颜色编号", "左のペイント色番号"],
  PaintRightC: ["右侧彩绘颜色编号", "右のペイント色番号"],
  Freckles: ["雀斑", "そばかす"],
  ColorFreckles: ["雀斑颜色编号", "そばかすの色番号"],
  MascaraType: ["睫毛膏类型编号", "マスカラの種類番号"],
  Eyeliner: ["眼线", "アイライン"],
  Cheek: ["腮红", "チーク"],
  Lips: ["唇彩", "リップ"],
  Mascara: ["睫毛膏", "マスカラ"],
  ColorEyeliner: ["眼线颜色编号", "アイラインの色番号"],
  ColorCheek: ["腮红颜色编号", "チークの色番号"],
  ColorLips: ["唇彩颜色编号", "リップの色番号"],
};
export type AppearanceLanguage = "zh" | "ja" | "en";
export function appearanceOptionName(
  raw: string,
  language: AppearanceLanguage,
): string {
  if (/^_\d+$/.test(raw))
    return `${language === "zh" ? "未命名" : language === "ja" ? "名称なし" : "Unnamed"} #${raw.slice(1)}`;
  if (language === "en") return raw.replaceAll("_", " ");
  const direct = names[raw]?.[language === "zh" ? 0 : 1];
  if (direct) return direct;
  if (raw.endsWith("_Glitched"))
    return `${appearanceOptionName(raw.slice(0, -9), language)} (${language === "zh" ? "显示异常" : "表示不具合"})`;
  const color = raw.match(
    /_(Navy_Blue|Lime_Green|Pale_Pink|Black|Red|Green|Blue|White|Yellow|Pink|Purple|Gray|Orange|Brown|Beige|Olive|Aqua|Gold|Silver|Metal|Denim|Satin)$/,
  )?.[1];
  if (color && names[raw.slice(0, -color.length - 1)])
    return `${appearanceOptionName(raw.slice(0, -color.length - 1), language)} · ${appearanceOptionName(color, language)}`;
  return raw.replaceAll("_", " ");
}
export function appearanceFieldName(
  key: string,
  language: AppearanceLanguage,
): string {
  const special = key.match(/^(Unknown|Unused)(\d+)$/);
  if (special)
    return `${language === "zh" ? (special[1] === "Unknown" ? "未知字段" : "未使用字段") : language === "ja" ? (special[1] === "Unknown" ? "不明な項目" : "未使用の項目") : special[1]} ${special[2]}`;
  return language === "en"
    ? key.replace(/([a-z])([A-Z])/g, "$1 $2")
    : (appearanceFieldNames[key]?.[language === "zh" ? 0 : 1] ?? key);
}
